version: 2
updates:
  # --- GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "dtobe"
      - "jonnunezalvarez"

  # --- Root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "production"
    reviewers:
      - "dtobe"
      - "jonnunezalvarez"
