env:
  browser: true
  commonjs: true
  es6: true
  jest: true
extends: standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  semi: [2, "always"],
  space-before-function-paren: ["error", "never"]
}
