sudo: false
language: node_js
node_js:
- node
- lts/*
- 10
os:
- linux
- osx
branches:
  all_branches: true
cache: yarn
install:
- yarn install --frozen-lockfile
before_script:
- yarn lint
after_script:
- yarn coveralls
