# This workflow will do a clean install of node dependencies and run tests across different versions of node and operating systems
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    name: ESLint
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: yarn --frozen-lockfile
    - run: yarn lint-report
    - uses: ataylorme/eslint-annotate-action@1.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        report-json: "eslint_report.json"

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [10, 12, 14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-18.04
            node_version: 12.14.1

    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - run: yarn --frozen-lockfile
    - run: yarn test

  coverage:
    runs-on: ubuntu-latest
    name: Coveralls
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: yarn --frozen-lockfile
    - run: yarn coverage
    - uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
