# This workflow will do a clean install of node dependencies and run tests across different versions of node and operating systems
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    name: ESLint
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn --frozen-lockfile
    - run: yarn lint-report
    - uses: ataylorme/eslint-annotate-action@1.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        report-json: "eslint_report.json"

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest, macos-latest]

    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - run: yarn --frozen-lockfile
    - run: yarn test

  coverage:
    runs-on: ubuntu-latest
    name: Coveralls
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn --frozen-lockfile
    - run: yarn coverage
    - uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
